/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package flink.application.batch;

import java.util.Arrays;
import java.util.Set;

import org.apache.flink.api.java.ExecutionEnvironment;

import com.google.common.collect.Sets;
import com.google.common.io.Resources;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

/*
 * Filter movie with a specific genre
 */
public class ApplicationOne {
    
    @Getter
    @AllArgsConstructor
    @ToString
    static class Movie {
        private String name;
        private Set<String> genres;
    }
    
    public static void main(String[] args) throws Exception {
        
        ExecutionEnvironment env = ExecutionEnvironment.getExecutionEnvironment();
        
        //env.getConfig().registerTypeWithKryoSerializer(ImmutableSet.class, ImmutableSetSerializer.class);
        //env.getConfig().registerTypeWithKryoSerializer(ImmutableCollection.class, ImmutableSetSerializer.class);
        
        env.readCsvFile(Resources.getResource("movielens/movies.csv").getPath())
            .ignoreFirstLine()
            .ignoreInvalidLines()
            .parseQuotedStrings('"')
            .types(Long.class, String.class, String.class)
            .map(tuple -> new Movie(tuple.f1, Sets.newHashSet(Arrays.asList(tuple.f2.split("\\|")))))
            .filter(movie -> movie.getGenres().contains("Comedy"))
            .print();
    }
}
